[2025-01-24T09:39:14.463-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T09:39:14.469-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ReadPacTrat.readPacTrat scheduled__2020-03-18T06:15:00+00:00 [queued]>
[2025-01-24T09:39:14.474-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ReadPacTrat.readPacTrat scheduled__2020-03-18T06:15:00+00:00 [queued]>
[2025-01-24T09:39:14.474-0300] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-24T09:39:14.486-0300] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): readPacTrat> on 2020-03-18 06:15:00+00:00
[2025-01-24T09:39:14.490-0300] {standard_task_runner.py:72} INFO - Started process 21601 to run task
[2025-01-24T09:39:14.492-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ReadPacTrat', 'readPacTrat', 'scheduled__2020-03-18T06:15:00+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/DAGFiltroPacientesTratamento.py', '--cfg-path', '/tmp/tmpexr9nl47']
[2025-01-24T09:39:14.493-0300] {standard_task_runner.py:105} INFO - Job 335: Subtask readPacTrat
[2025-01-24T09:39:14.515-0300] {task_command.py:467} INFO - Running <TaskInstance: ReadPacTrat.readPacTrat scheduled__2020-03-18T06:15:00+00:00 [running]> on host lucas-Aspire-A514-54
[2025-01-24T09:39:14.649-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lucas' AIRFLOW_CTX_DAG_ID='ReadPacTrat' AIRFLOW_CTX_TASK_ID='readPacTrat' AIRFLOW_CTX_EXECUTION_DATE='2020-03-18T06:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-03-18T06:15:00+00:00'
[2025-01-24T09:39:14.649-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-24T09:39:14.649-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-24T09:39:14.649-0300] {logging_mixin.py:190} INFO - Current task name:readPacTrat state:running start_date:2025-01-24 12:39:14.469434+00:00
[2025-01-24T09:39:14.649-0300] {logging_mixin.py:190} INFO - Dag name:ReadPacTrat and current dag run status:running
[2025-01-24T09:39:14.649-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T09:39:14.721-0300] {logging_mixin.py:190} WARNING - /home/lucas/airflow/dags/DAGFiltroPacientesTratamento.py:9 DtypeWarning: Columns (8,34) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-01-24T09:39:14.854-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow/dags/DAGFiltroPacientesTratamento.py", line 38, in read_excel
    df_temp = df.join(df_cidades.set_index('municipio'), on='Cidade', how='inner')[['Cidade','latitude', 'longitude']]
                      ^^^^^^^^^^
NameError: name 'df_cidades' is not defined
[2025-01-24T09:39:14.865-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-24T09:39:14.865-0300] {logging_mixin.py:190} INFO - Task start:2025-01-24 12:39:14.469434+00:00 end:2025-01-24 12:39:14.864732+00:00 duration:0.395298
[2025-01-24T09:39:14.865-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): readPacTrat> dag:<DAG: ReadPacTrat> dagrun:<DagRun ReadPacTrat @ 2020-03-18 06:15:00+00:00: scheduled__2020-03-18T06:15:00+00:00, state:running, queued_at: 2025-01-24 12:24:17.752772+00:00. externally triggered: False>
[2025-01-24T09:39:14.865-0300] {logging_mixin.py:190} INFO - Failure caused by name 'df_cidades' is not defined
[2025-01-24T09:39:14.865-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ReadPacTrat, task_id=readPacTrat, run_id=scheduled__2020-03-18T06:15:00+00:00, execution_date=20200318T061500, start_date=20250124T123914, end_date=20250124T123914
[2025-01-24T09:39:14.877-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T09:39:14.878-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 335 for task readPacTrat (name 'df_cidades' is not defined; 21601)
Traceback (most recent call last):
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow/dags/DAGFiltroPacientesTratamento.py", line 38, in read_excel
    df_temp = df.join(df_cidades.set_index('municipio'), on='Cidade', how='inner')[['Cidade','latitude', 'longitude']]
                      ^^^^^^^^^^
NameError: name 'df_cidades' is not defined
[2025-01-24T09:39:14.905-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T09:39:14.914-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T09:39:14.915-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
