[2025-01-26T22:33:24.133-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T22:33:24.139-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: InsertIntoElastic.inject_data_into_es scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-01-26T22:33:24.143-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: InsertIntoElastic.inject_data_into_es scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-01-26T22:33:24.143-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T22:33:24.154-0300] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): inject_data_into_es> on 2023-01-01 00:00:00+00:00
[2025-01-26T22:33:24.158-0300] {standard_task_runner.py:72} INFO - Started process 116431 to run task
[2025-01-26T22:33:24.160-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'InsertIntoElastic', 'inject_data_into_es', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '5842', '--raw', '--subdir', 'DAGS_FOLDER/DAGInjectElastic.py', '--cfg-path', '/tmp/tmpvonx2qaj']
[2025-01-26T22:33:24.162-0300] {standard_task_runner.py:105} INFO - Job 5842: Subtask inject_data_into_es
[2025-01-26T22:33:24.186-0300] {task_command.py:467} INFO - Running <TaskInstance: InsertIntoElastic.inject_data_into_es scheduled__2023-01-01T00:00:00+00:00 [running]> on host lucas-Aspire-A514-54
[2025-01-26T22:33:24.231-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lucas' AIRFLOW_CTX_DAG_ID='InsertIntoElastic' AIRFLOW_CTX_TASK_ID='inject_data_into_es' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2025-01-26T22:33:24.231-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T22:33:24.502-0300] {_transport.py:349} INFO - PUT http://localhost:9200/_bulk [status:200 duration:0.073s]
[2025-01-26T22:33:24.511-0300] {DAGInjectElastic.py:93} ERROR - Error uploading data to Elasticsearch: 500 document(s) failed to index.
[2025-01-26T22:33:24.515-0300] {python.py:240} INFO - Done. Returned value was: False
[2025-01-26T22:33:24.542-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T22:33:24.542-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=InsertIntoElastic, task_id=inject_data_into_es, run_id=scheduled__2023-01-01T00:00:00+00:00, execution_date=20230101T000000, start_date=20250127T013324, end_date=20250127T013324
[2025-01-26T22:33:24.573-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T22:33:24.581-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T22:33:24.581-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
